module.exports.BackbonePagination = require('./app/js/components/BackbonePagination.jsx')
module.exports.Table = require('./app/js/components/Table.jsx')
module.exports.PageableTable = require('./app/js/components/PageableTable.jsx')
module.exports.FilterablePageableTable = require('./app/js/components/FilterablePageableTable.jsx')
module.exports.FilterSearch = require('./app/js/components/FilterSearch.jsx')
